# These are supported funding model platforms

# Remove github line if you're not enrolled in GitHub Sponsors
# github: levidang306
custom: ["https://github.com/levidang306/chores-utils/blob/main/SPONSOR.md"]

